    /*                                           
 * To change this license header, choose License Headers in Project Properties.                                          
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ksufinal;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Ricky
 */
public class Menu extends javax.swing.JFrame {
    AddTransaction transactionClass = new AddTransaction();
    NewProduct NewProductClass = new NewProduct();
    NewSupplier NewSupplierClass = new NewSupplier();
    NewUnit NewUnitClass = new NewUnit();
    NewCategory NewCategoryClass = new NewCategory();
    NewSubCategory NewSubCategoryClass = new NewSubCategory();
    NewBranch NewBranchClass = new NewBranch();
    ViewProducts ViewProductsClass = new ViewProducts();
    ViewTransactions ViewTransactionsClass = new ViewTransactions();
    ViewSupplier ViewSupplierClass = new ViewSupplier();
    ViewBranch ViewBranchClass = new ViewBranch();
    ViewCategory ViewCategoryClass = new ViewCategory();
    ViewSubCategory ViewSubCategoryClass = new ViewSubCategory();
    ViewUnit ViewUnitClass = new ViewUnit();
    Report ReportClass = new Report();
    EditCategory EditCategoryClass = new EditCategory();
    EditSubCategory EditSubCategoryClass = new EditSubCategory();
    EditProduct EditProductClass = new EditProduct();
    EditTransaction EditTransactionClass = new EditTransaction();
    EditUnit EditUnitClass = new EditUnit();
    EditBranch EditBranchClass = new EditBranch();
    EditSupplier EditSupplierClass = new EditSupplier();
    EditUser EditUserClass = new EditUser();
    EditInventoryInfo EditInventoryInfoClass = new EditInventoryInfo();
    int indexTab = 0;

    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        companyName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        editItemsLabel = new javax.swing.JLabel();
        transactionLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        viewLabel = new javax.swing.JLabel();
        reportLabel = new javax.swing.JLabel();
        newItemsLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        newProductBtn = new javax.swing.JButton();
        newUnitBtn = new javax.swing.JButton();
        newSupplierBtn = new javax.swing.JButton();
        newBranchBtn = new javax.swing.JButton();
        newCategoryBtn = new javax.swing.JButton();
        newSubCategoryBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        editProductBtn = new javax.swing.JButton();
        editUnitBtn = new javax.swing.JButton();
        editSuppliersBtn = new javax.swing.JButton();
        editBranchBtn = new javax.swing.JButton();
        editCategoryBtn = new javax.swing.JButton();
        editInventoryInfoBtn = new javax.swing.JButton();
        editSubCategoryBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        receiveWithdrawItemsBtn = new javax.swing.JButton();
        editTransactionBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        viewTransactionBtn = new javax.swing.JButton();
        viewProductsBtn = new javax.swing.JButton();
        viewBranchBtn = new javax.swing.JButton();
        viewCategoryBtn = new javax.swing.JButton();
        viewSupplierBtn = new javax.swing.JButton();
        viewUnitsBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lastNameTF = new javax.swing.JLabel();
        fileLocationLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        editFileBtn = new javax.swing.JButton();
        loadBackupBtn = new javax.swing.JButton();
        saveBackupBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(178, 190, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 52, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(45, 52, 54));
        jButton7.setForeground(new java.awt.Color(250, 250, 250));
        jButton7.setText("X");
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 10, 50, 20));

        jButton8.setBackground(new java.awt.Color(45, 52, 54));
        jButton8.setForeground(new java.awt.Color(250, 250, 250));
        jButton8.setText("-");
        jButton8.setBorder(null);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.setMaximumSize(new java.awt.Dimension(7, 15));
        jButton8.setMinimumSize(new java.awt.Dimension(7, 15));
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 50, 20));

        companyName.setBackground(new java.awt.Color(153, 153, 153));
        companyName.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        companyName.setForeground(new java.awt.Color(255, 255, 255));
        companyName.setText("Title Text");
        companyName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        companyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyNameMouseClicked(evt);
            }
        });
        jPanel2.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 770, 100));

        jPanel3.setBackground(new java.awt.Color(99, 110, 114));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(99, 110, 114));
        jButton1.setText("Log out");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 110, -1));

        editItemsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gEdititems.png"))); // NOI18N
        editItemsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editItemsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editItemsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editItemsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editItemsLabelMouseExited(evt);
            }
        });
        jPanel3.add(editItemsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        transactionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gTrans.png"))); // NOI18N
        transactionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transactionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactionLabelMouseExited(evt);
            }
        });
        jPanel3.add(transactionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gUsers.png"))); // NOI18N
        userLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userLabelMouseExited(evt);
            }
        });
        jPanel3.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        viewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gView.png"))); // NOI18N
        viewLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewLabelMouseExited(evt);
            }
        });
        jPanel3.add(viewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        reportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gReport.png"))); // NOI18N
        reportLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportLabelMouseExited(evt);
            }
        });
        jPanel3.add(reportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        newItemsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gNewitems.png"))); // NOI18N
        newItemsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newItemsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newItemsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newItemsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newItemsLabelMouseExited(evt);
            }
        });
        jPanel3.add(newItemsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 540));

        jTabbedPane1.setBackground(new java.awt.Color(99, 110, 114));
        jTabbedPane1.setForeground(new java.awt.Color(99, 110, 114));
        jTabbedPane1.setEnabled(false);

        jPanel4.setBackground(new java.awt.Color(178, 190, 195));

        newProductBtn.setBackground(new java.awt.Color(178, 190, 195));
        newProductBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        newProductBtn.setForeground(new java.awt.Color(250, 250, 250));
        newProductBtn.setText("New Product");
        newProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newProductBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newProductBtnMouseExited(evt);
            }
        });
        newProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductBtnActionPerformed(evt);
            }
        });

        newUnitBtn.setBackground(new java.awt.Color(178, 190, 195));
        newUnitBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        newUnitBtn.setForeground(new java.awt.Color(250, 250, 250));
        newUnitBtn.setText("New Unit");
        newUnitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newUnitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newUnitBtnMouseExited(evt);
            }
        });
        newUnitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUnitBtnActionPerformed(evt);
            }
        });

        newSupplierBtn.setBackground(new java.awt.Color(178, 190, 195));
        newSupplierBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        newSupplierBtn.setForeground(new java.awt.Color(250, 250, 250));
        newSupplierBtn.setText("New Supplier");
        newSupplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newSupplierBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newSupplierBtnMouseExited(evt);
            }
        });
        newSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSupplierBtnActionPerformed(evt);
            }
        });

        newBranchBtn.setBackground(new java.awt.Color(178, 190, 195));
        newBranchBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        newBranchBtn.setForeground(new java.awt.Color(250, 250, 250));
        newBranchBtn.setText("New Branch");
        newBranchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newBranchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newBranchBtnMouseExited(evt);
            }
        });
        newBranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBranchBtnActionPerformed(evt);
            }
        });

        newCategoryBtn.setBackground(new java.awt.Color(178, 190, 195));
        newCategoryBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        newCategoryBtn.setForeground(new java.awt.Color(250, 250, 250));
        newCategoryBtn.setText("New Category");
        newCategoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newCategoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newCategoryBtnMouseExited(evt);
            }
        });
        newCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCategoryBtnActionPerformed(evt);
            }
        });

        newSubCategoryBtn.setBackground(new java.awt.Color(178, 190, 195));
        newSubCategoryBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        newSubCategoryBtn.setForeground(new java.awt.Color(250, 250, 250));
        newSubCategoryBtn.setText("New Sub-Category");
        newSubCategoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newSubCategoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newSubCategoryBtnMouseExited(evt);
            }
        });
        newSubCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSubCategoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newUnitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBranchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSubCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newUnitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBranchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSubCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel5.setBackground(new java.awt.Color(178, 190, 195));

        editProductBtn.setBackground(new java.awt.Color(178, 190, 195));
        editProductBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editProductBtn.setForeground(new java.awt.Color(250, 250, 250));
        editProductBtn.setText("Edit Product");
        editProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProductBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProductBtnMouseExited(evt);
            }
        });
        editProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductBtnActionPerformed(evt);
            }
        });

        editUnitBtn.setBackground(new java.awt.Color(178, 190, 195));
        editUnitBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editUnitBtn.setForeground(new java.awt.Color(250, 250, 250));
        editUnitBtn.setText("Edit Unit");
        editUnitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editUnitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editUnitBtnMouseExited(evt);
            }
        });
        editUnitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUnitBtnActionPerformed(evt);
            }
        });

        editSuppliersBtn.setBackground(new java.awt.Color(178, 190, 195));
        editSuppliersBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editSuppliersBtn.setForeground(new java.awt.Color(250, 250, 250));
        editSuppliersBtn.setText("Edit Suppliers");
        editSuppliersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editSuppliersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editSuppliersBtnMouseExited(evt);
            }
        });
        editSuppliersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSuppliersBtnActionPerformed(evt);
            }
        });

        editBranchBtn.setBackground(new java.awt.Color(178, 190, 195));
        editBranchBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editBranchBtn.setForeground(new java.awt.Color(250, 250, 250));
        editBranchBtn.setText("Edit Branch");
        editBranchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editBranchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editBranchBtnMouseExited(evt);
            }
        });
        editBranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBranchBtnActionPerformed(evt);
            }
        });

        editCategoryBtn.setBackground(new java.awt.Color(178, 190, 195));
        editCategoryBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editCategoryBtn.setForeground(new java.awt.Color(250, 250, 250));
        editCategoryBtn.setText("Edit Category");
        editCategoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editCategoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editCategoryBtnMouseExited(evt);
            }
        });
        editCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryBtnActionPerformed(evt);
            }
        });

        editInventoryInfoBtn.setBackground(new java.awt.Color(178, 190, 195));
        editInventoryInfoBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editInventoryInfoBtn.setForeground(new java.awt.Color(250, 250, 250));
        editInventoryInfoBtn.setText("Edit Inventory Info");
        editInventoryInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editInventoryInfoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editInventoryInfoBtnMouseExited(evt);
            }
        });
        editInventoryInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInventoryInfoBtnActionPerformed(evt);
            }
        });

        editSubCategoryBtn.setBackground(new java.awt.Color(178, 190, 195));
        editSubCategoryBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editSubCategoryBtn.setForeground(new java.awt.Color(250, 250, 250));
        editSubCategoryBtn.setText("Edit Sub-Category");
        editSubCategoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editSubCategoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editSubCategoryBtnMouseExited(evt);
            }
        });
        editSubCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSubCategoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(editSubCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(editSuppliersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addComponent(editBranchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(editProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editUnitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(editCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editInventoryInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editUnitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSuppliersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBranchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editInventoryInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(editSubCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel5);

        jPanel6.setBackground(new java.awt.Color(178, 190, 195));

        receiveWithdrawItemsBtn.setBackground(new java.awt.Color(178, 190, 195));
        receiveWithdrawItemsBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        receiveWithdrawItemsBtn.setForeground(new java.awt.Color(250, 250, 250));
        receiveWithdrawItemsBtn.setText("Recieve/Withdraw Items");
        receiveWithdrawItemsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                receiveWithdrawItemsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                receiveWithdrawItemsBtnMouseExited(evt);
            }
        });
        receiveWithdrawItemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveWithdrawItemsBtnActionPerformed(evt);
            }
        });

        editTransactionBtn.setBackground(new java.awt.Color(178, 190, 195));
        editTransactionBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        editTransactionBtn.setForeground(new java.awt.Color(250, 250, 250));
        editTransactionBtn.setText("Edit Transaction");
        editTransactionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editTransactionBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editTransactionBtnMouseExited(evt);
            }
        });
        editTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTransactionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(receiveWithdrawItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(editTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiveWithdrawItemsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel6);

        jPanel7.setBackground(new java.awt.Color(178, 190, 195));

        viewTransactionBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewTransactionBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        viewTransactionBtn.setForeground(new java.awt.Color(250, 250, 250));
        viewTransactionBtn.setText("View Transaction");
        viewTransactionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewTransactionBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewTransactionBtnMouseExited(evt);
            }
        });
        viewTransactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionBtnActionPerformed(evt);
            }
        });

        viewProductsBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewProductsBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        viewProductsBtn.setForeground(new java.awt.Color(250, 250, 250));
        viewProductsBtn.setText("View Products");
        viewProductsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewProductsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewProductsBtnMouseExited(evt);
            }
        });
        viewProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductsBtnActionPerformed(evt);
            }
        });

        viewBranchBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewBranchBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        viewBranchBtn.setForeground(new java.awt.Color(250, 250, 250));
        viewBranchBtn.setText("View Branch");
        viewBranchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewBranchBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewBranchBtnMouseExited(evt);
            }
        });
        viewBranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBranchBtnActionPerformed(evt);
            }
        });

        viewCategoryBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewCategoryBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        viewCategoryBtn.setForeground(new java.awt.Color(250, 250, 250));
        viewCategoryBtn.setText("View Category");
        viewCategoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewCategoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewCategoryBtnMouseExited(evt);
            }
        });
        viewCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCategoryBtnActionPerformed(evt);
            }
        });

        viewSupplierBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewSupplierBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        viewSupplierBtn.setForeground(new java.awt.Color(250, 250, 250));
        viewSupplierBtn.setText("View Suppliers");
        viewSupplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewSupplierBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewSupplierBtnMouseExited(evt);
            }
        });
        viewSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierBtnActionPerformed(evt);
            }
        });

        viewUnitsBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewUnitsBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        viewUnitsBtn.setForeground(new java.awt.Color(250, 250, 250));
        viewUnitsBtn.setText("View Units");
        viewUnitsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewUnitsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewUnitsBtnMouseExited(evt);
            }
        });
        viewUnitsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUnitsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewUnitsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBranchBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProductsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCategoryBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTransactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBranchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewUnitsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel7);

        jPanel8.setBackground(new java.awt.Color(178, 190, 195));

        jButton16.setText("Create Report");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jButton16)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButton16)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel8);

        jPanel9.setBackground(new java.awt.Color(178, 190, 195));

        jButton17.setText("Edit User");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jButton17)
                .addContainerGap(354, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton17)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", jPanel9);

        jPanel10.setBackground(new java.awt.Color(178, 190, 195));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Last Name:");

        welcomeLabel.setBackground(new java.awt.Color(153, 153, 153));
        welcomeLabel.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Title Text");
        welcomeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        welcomeLabel.setMaximumSize(new java.awt.Dimension(10000, 1000));

        firstNameTF.setBackground(new java.awt.Color(153, 153, 153));
        firstNameTF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        firstNameTF.setText("Hello");

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("First Name:");

        lastNameTF.setBackground(new java.awt.Color(153, 153, 153));
        lastNameTF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lastNameTF.setText("Hello");

        fileLocationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setText("Back-up File Location:");

        editFileBtn.setText("Edit");
        editFileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFileBtnActionPerformed(evt);
            }
        });

        loadBackupBtn.setText("Load Back-up File");
        loadBackupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadBackupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBackupBtnActionPerformed(evt);
            }
        });

        saveBackupBtn.setText("Save Back-up File");
        saveBackupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBackupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBackupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadBackupBtn)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editFileBtn))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTF)
                            .addComponent(firstNameTF)))
                    .addComponent(saveBackupBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(firstNameTF))
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTF)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(editFileBtn))
                .addGap(39, 39, 39)
                .addComponent(saveBackupBtn)
                .addGap(18, 18, 18)
                .addComponent(loadBackupBtn)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab7", jPanel10);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 630, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            jTabbedPane1.setSelectedIndex(6);
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int log = 0;
        log = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Warning",JOptionPane.YES_NO_OPTION);
        if(log == JOptionPane.YES_OPTION){
            this.dispose();
            Login loginClass = new Login();
            loginClass.setVisible(true);
            loginClass.setLocationRelativeTo(null);
            saveBackUp();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //usernameTF.setText(Login.userName);
        firstNameTF.setText(Login.firstName);
        lastNameTF.setText(Login.lastName);
//        jTabbedPane1.setSelectedIndex(6);
//        System.out.print("window opened");
//        if (!Login.admin){
//            EditItemsMenu.setVisible(false);
//            EditTransactionMenu.setVisible(false);
//            UsersMainMenu.setVisible(false);
//        }else{
//            EditItemsMenu.setVisible(true);
//            EditTransactionMenu.setVisible(true);
//            UsersMainMenu.setVisible(true);
//
//        }
    }//GEN-LAST:event_formWindowActivated

    private void newProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductBtnActionPerformed
        // TODO add your handling code here:
         NewProductClass.setVisible(true);
        NewProductClass.setDefaultCloseOperation(NewProductClass.DISPOSE_ON_CLOSE);
        NewProductClass.setLocationRelativeTo(null);
        this.setVisible(false);
        NewProductClass.openWindowAction();
    }//GEN-LAST:event_newProductBtnActionPerformed

    private void editItemsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editItemsLabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);


    }//GEN-LAST:event_editItemsLabelMouseClicked

    private void transactionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionLabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);

    }//GEN-LAST:event_transactionLabelMouseClicked

    private void newItemsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newItemsLabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_newItemsLabelMouseClicked

    private void viewLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLabelMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_viewLabelMouseClicked

    private void reportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseClicked
        // TODO add your handling code here:
        //jTabbedPane1.setSelectedIndex(4);
         

        ReportClass.setVisible(true);
        ReportClass.setDefaultCloseOperation(ReportClass.DISPOSE_ON_CLOSE);
        ReportClass.setLocationRelativeTo(null);
        this.setVisible(false);
        ReportClass.openWindowAction();
    }//GEN-LAST:event_reportLabelMouseClicked

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        // TODO add your handling code here:
        
        if(Login.admin == true){            
            EditUserClass.setVisible(true);
            EditUserClass.setDefaultCloseOperation(EditUserClass.DISPOSE_ON_CLOSE);
            EditUserClass.setLocationRelativeTo(null);  
            this.setVisible(false);
            EditUserClass.openWindowAction();
        }
        else{
              JOptionPane.showMessageDialog(this,"You must be an Admin to access this tab");
        }
    }//GEN-LAST:event_userLabelMouseClicked

    private void editItemsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editItemsLabelMouseEntered
        editItemsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/wEdititems.png")));
    }//GEN-LAST:event_editItemsLabelMouseEntered

    private void newItemsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newItemsLabelMouseEntered
        newItemsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/wNewitems.png")));
       
    }//GEN-LAST:event_newItemsLabelMouseEntered

    private void transactionLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionLabelMouseEntered
        transactionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/wTrans.png")));
        
    }//GEN-LAST:event_transactionLabelMouseEntered

    private void userLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseEntered
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/wUsers.png")));
    }//GEN-LAST:event_userLabelMouseEntered

    private void newProductBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProductBtnMouseEntered
        // TODO add your handling code here:
        newProductBtn.setBackground(new java.awt.Color(250, 250, 250));
        newProductBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_newProductBtnMouseEntered

    private void newProductBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProductBtnMouseExited
        // TODO add your handling code here:
        newProductBtn.setBackground(new java.awt.Color(178, 190, 195));
        newProductBtn.setForeground(new java.awt.Color(250, 250, 250));

    }//GEN-LAST:event_newProductBtnMouseExited

    private void newUnitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUnitBtnMouseEntered
        // TODO add your handling code here:
        newUnitBtn.setBackground(new java.awt.Color(250, 250, 250));
        newUnitBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_newUnitBtnMouseEntered

    private void newUnitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUnitBtnMouseExited
        // TODO add your handling code here:
        newUnitBtn.setBackground(new java.awt.Color(178, 190, 195));
        newUnitBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_newUnitBtnMouseExited

    private void newUnitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUnitBtnActionPerformed
        // TODO add your handling code here:
        NewUnitClass.setVisible(true);
        NewUnitClass.setDefaultCloseOperation(NewUnitClass.DISPOSE_ON_CLOSE);
        NewUnitClass.setLocationRelativeTo(null);
        this.setVisible(false);
        NewUnitClass.openWindowAction();
    }//GEN-LAST:event_newUnitBtnActionPerformed

    private void newSupplierBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSupplierBtnMouseEntered
        // TODO add your handling code here:
        newSupplierBtn.setBackground(new java.awt.Color(250, 250, 250));
        newSupplierBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_newSupplierBtnMouseEntered

    private void newSupplierBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSupplierBtnMouseExited
        // TODO add your handling code here:
        newSupplierBtn.setBackground(new java.awt.Color(178, 190, 195));
        newSupplierBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_newSupplierBtnMouseExited

    private void newSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSupplierBtnActionPerformed
        // TODO add your handling code here:
        NewSupplierClass.setVisible(true);
        NewSupplierClass.setDefaultCloseOperation(NewSupplierClass.DISPOSE_ON_CLOSE);
        NewSupplierClass.setLocationRelativeTo(null);
        this.setVisible(false);
        NewSupplierClass.openWindowAction();
    }//GEN-LAST:event_newSupplierBtnActionPerformed

    private void newBranchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBranchBtnMouseEntered
        // TODO add your handling code here:
        newBranchBtn.setBackground(new java.awt.Color(250, 250, 250));
        newBranchBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_newBranchBtnMouseEntered

    private void newBranchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBranchBtnMouseExited
        // TODO add your handling code here:
        newBranchBtn.setBackground(new java.awt.Color(178, 190, 195));
        newBranchBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_newBranchBtnMouseExited

    private void newBranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBranchBtnActionPerformed
        // TODO add your handling code here:
        
        NewBranchClass.setVisible(true);
        NewBranchClass.setDefaultCloseOperation(NewBranchClass.DISPOSE_ON_CLOSE);
        NewBranchClass.setLocationRelativeTo(null);
        this.setVisible(false);
        NewBranchClass.openWindowAction();
    }//GEN-LAST:event_newBranchBtnActionPerformed

    private void newCategoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCategoryBtnMouseEntered
        // TODO add your handling code here:
        newCategoryBtn.setBackground(new java.awt.Color(250, 250, 250));
        newCategoryBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_newCategoryBtnMouseEntered

    private void newCategoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newCategoryBtnMouseExited
        // TODO add your handling code here:
        newCategoryBtn.setBackground(new java.awt.Color(178, 190, 195));
        newCategoryBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_newCategoryBtnMouseExited

    private void newCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCategoryBtnActionPerformed
        // TODO add your handling code here:
        NewCategoryClass.setVisible(true);
        NewCategoryClass.setDefaultCloseOperation(NewCategoryClass.DISPOSE_ON_CLOSE);
        NewCategoryClass.setLocationRelativeTo(null);
        this.setVisible(false);
        NewCategoryClass.openWindowAction();
    }//GEN-LAST:event_newCategoryBtnActionPerformed

    private void editProductBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProductBtnMouseEntered
        // TODO add your handling code here:
        editProductBtn.setBackground(new java.awt.Color(250, 250, 250));
        editProductBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_editProductBtnMouseEntered

    private void editProductBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProductBtnMouseExited
        // TODO add your handling code here:
        editProductBtn.setBackground(new java.awt.Color(178, 190, 195));
        editProductBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_editProductBtnMouseExited

    private void editProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductBtnActionPerformed
        // TODO add your handling code here:
        
        EditProductClass.setVisible(true);
        EditProductClass.setDefaultCloseOperation(EditProductClass.DISPOSE_ON_CLOSE);
        EditProductClass.setLocationRelativeTo(null);
        this.setVisible(false);
        EditProductClass.openWindowAction();
    }//GEN-LAST:event_editProductBtnActionPerformed

    private void editUnitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUnitBtnMouseEntered
        // TODO add your handling code here:
        editUnitBtn.setBackground(new java.awt.Color(250, 250, 250));
        editUnitBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_editUnitBtnMouseEntered

    private void editUnitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editUnitBtnMouseExited
        // TODO add your handling code here:
        editUnitBtn.setBackground(new java.awt.Color(178, 190, 195));
        editUnitBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_editUnitBtnMouseExited

    private void editUnitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUnitBtnActionPerformed
        // TODO add your handling code here:
        
        EditUnitClass.setVisible(true);
        EditUnitClass.setDefaultCloseOperation(EditUnitClass.DISPOSE_ON_CLOSE);
        EditUnitClass.setLocationRelativeTo(null);
        this.setVisible(false);
        EditUnitClass.openWindowAction();
    }//GEN-LAST:event_editUnitBtnActionPerformed

    private void editSuppliersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSuppliersBtnMouseEntered
        // TODO add your handling code here:
        editSuppliersBtn.setBackground(new java.awt.Color(250, 250, 250));
        editSuppliersBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_editSuppliersBtnMouseEntered

    private void editSuppliersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSuppliersBtnMouseExited
        // TODO add your handling code here:
        editSuppliersBtn.setBackground(new java.awt.Color(178, 190, 195));
editSuppliersBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_editSuppliersBtnMouseExited

    private void editSuppliersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSuppliersBtnActionPerformed
        // TODO add your handling code here:
         EditSupplierClass.setVisible(true);
        EditSupplierClass.setDefaultCloseOperation(EditSupplierClass.DISPOSE_ON_CLOSE);
        EditSupplierClass.setLocationRelativeTo(null);
        this.setVisible(false);
        EditSupplierClass.openWindowAction();
    }//GEN-LAST:event_editSuppliersBtnActionPerformed

    private void editBranchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBranchBtnMouseEntered
        // TODO add your handling code here:
        editBranchBtn.setBackground(new java.awt.Color(250, 250, 250));
        editBranchBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_editBranchBtnMouseEntered

    private void editBranchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBranchBtnMouseExited
        // TODO add your handling code here:
        editBranchBtn.setBackground(new java.awt.Color(178, 190, 195));
        editBranchBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_editBranchBtnMouseExited

    private void editBranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBranchBtnActionPerformed
        // TODO add your handling code here:
        
        
        EditBranchClass.setVisible(true);
        EditBranchClass.setDefaultCloseOperation(EditBranchClass.DISPOSE_ON_CLOSE);
        EditBranchClass.setLocationRelativeTo(null);
        this.setVisible(false);
        EditBranchClass.openWindowAction();
    }//GEN-LAST:event_editBranchBtnActionPerformed

    private void receiveWithdrawItemsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiveWithdrawItemsBtnMouseEntered
        receiveWithdrawItemsBtn.setBackground(new java.awt.Color(250, 250, 250));
        receiveWithdrawItemsBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_receiveWithdrawItemsBtnMouseEntered

    private void receiveWithdrawItemsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiveWithdrawItemsBtnMouseExited
        // TODO add your handling code here:
        receiveWithdrawItemsBtn.setBackground(new java.awt.Color(178, 190, 195));
        receiveWithdrawItemsBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_receiveWithdrawItemsBtnMouseExited

    private void receiveWithdrawItemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveWithdrawItemsBtnActionPerformed
        // TODO add your handling code here:
        
transactionClass.setVisible(true);
        transactionClass.setDefaultCloseOperation(transactionClass.DISPOSE_ON_CLOSE);
        transactionClass.setLocationRelativeTo(null);
        this.setVisible(false);
        transactionClass.openWindowAction();
    }//GEN-LAST:event_receiveWithdrawItemsBtnActionPerformed

    private void editTransactionBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTransactionBtnMouseEntered
        // TODO add your handling code here:
        editTransactionBtn.setBackground(new java.awt.Color(250, 250, 250));
        editTransactionBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_editTransactionBtnMouseEntered

    private void editTransactionBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editTransactionBtnMouseExited
        // TODO add your handling code here:
        editTransactionBtn.setBackground(new java.awt.Color(178, 190, 195));
        editTransactionBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_editTransactionBtnMouseExited

    private void editTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTransactionBtnActionPerformed
        // TODO add your handling code here:
        EditTransactionClass.setVisible(true);
        EditTransactionClass.setDefaultCloseOperation(EditTransactionClass.DISPOSE_ON_CLOSE);
        EditTransactionClass.setLocationRelativeTo(null);
        this.setVisible(false);
        EditTransactionClass.openWindowAction();
    }//GEN-LAST:event_editTransactionBtnActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        
        jButton1.setBackground(new java.awt.Color(178, 190, 195));
        jButton1.setForeground(new java.awt.Color(250, 250, 250));  
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(99,110,114));
         jButton1.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jButton1MouseExited

    private void editInventoryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInventoryMenuActionPerformed
        // TODO add your handling code here:
        
        EditInventoryInfoClass.setVisible(true);
        EditInventoryInfoClass.setDefaultCloseOperation(EditUserClass.DISPOSE_ON_CLOSE);
        EditInventoryInfoClass.setLocationRelativeTo(null);
        this.setVisible(false);
        EditInventoryInfoClass.openWindowAction();
    }//GEN-LAST:event_editInventoryMenuActionPerformed

    private void editCategoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCategoryBtnMouseEntered
        editCategoryBtn.setBackground(new java.awt.Color(250, 250, 250));
        editCategoryBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_editCategoryBtnMouseEntered

    private void editCategoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCategoryBtnMouseExited
        editCategoryBtn.setBackground(new java.awt.Color(178, 190, 195));
        editCategoryBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_editCategoryBtnMouseExited

    private void editCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategoryBtnActionPerformed
        EditCategoryClass.setVisible(true);
        EditCategoryClass.setDefaultCloseOperation(EditCategoryClass.DISPOSE_ON_CLOSE);
        EditCategoryClass.setLocationRelativeTo(null);  
        this.setVisible(false);
        EditCategoryClass.openWindowAction();
    }//GEN-LAST:event_editCategoryBtnActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        EditUserClass.setVisible(true);
        EditUserClass.setDefaultCloseOperation(EditUserClass.DISPOSE_ON_CLOSE);
        EditUserClass.setLocationRelativeTo(null);  
        this.setVisible(false);
        EditUserClass.openWindowAction();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
        jButton7.setBackground(new java.awt.Color(220,20,60));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
        jButton7.setBackground(new java.awt.Color(45,52,54));
        jButton7.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        // TODO add your handling code here:
        jButton8.setBackground(new java.awt.Color(250,250,250));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        // TODO add your handling code here:
        jButton8.setBackground(new java.awt.Color(45,52,54));
        jButton8.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        saveBackUp();
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void editInventoryInfoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editInventoryInfoBtnMouseEntered
        editInventoryInfoBtn.setBackground(new java.awt.Color(250, 250, 250));
        editInventoryInfoBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_editInventoryInfoBtnMouseEntered

    private void editInventoryInfoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editInventoryInfoBtnMouseExited
        editInventoryInfoBtn.setBackground(new java.awt.Color(178, 190, 195));
        editInventoryInfoBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_editInventoryInfoBtnMouseExited

    private void editInventoryInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInventoryInfoBtnActionPerformed
        // TODO add your handling code here:
        
        EditInventoryInfoClass.setVisible(true);
        EditInventoryInfoClass.setDefaultCloseOperation(EditInventoryInfoClass.DISPOSE_ON_CLOSE);
        EditInventoryInfoClass.setLocationRelativeTo(null);
        this.setVisible(false);
        EditInventoryInfoClass.openWindowAction();
    }//GEN-LAST:event_editInventoryInfoBtnActionPerformed

    private void viewUnitsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUnitsBtnActionPerformed
        // TODO add your handling code here:
        ViewUnitClass.setVisible(true);
        ViewUnitClass.setDefaultCloseOperation(ViewUnitClass.DISPOSE_ON_CLOSE);
        ViewUnitClass.setLocationRelativeTo(null);
        this.setVisible(false);
        ViewUnitClass.openWindowAction();
    }//GEN-LAST:event_viewUnitsBtnActionPerformed

    private void viewUnitsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUnitsBtnMouseExited
        viewUnitsBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewUnitsBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_viewUnitsBtnMouseExited

    private void viewUnitsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUnitsBtnMouseEntered
        viewUnitsBtn.setBackground(new java.awt.Color(250, 250, 250));
        viewUnitsBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_viewUnitsBtnMouseEntered

    private void viewSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierBtnActionPerformed
        ViewSupplierClass.setVisible(true);
        ViewSupplierClass.setDefaultCloseOperation(ViewSupplierClass.DISPOSE_ON_CLOSE);
        ViewSupplierClass.setLocationRelativeTo(null);
        ViewSupplierClass.openWindowAction();
        this.setVisible(false);
    }//GEN-LAST:event_viewSupplierBtnActionPerformed

    private void viewSupplierBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSupplierBtnMouseExited
        viewSupplierBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewSupplierBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_viewSupplierBtnMouseExited

    private void viewSupplierBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSupplierBtnMouseEntered
        viewSupplierBtn.setBackground(new java.awt.Color(250, 250, 250));
        viewSupplierBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_viewSupplierBtnMouseEntered

    private void viewCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCategoryBtnActionPerformed
        ViewCategoryClass.setVisible(true);
        ViewCategoryClass.setDefaultCloseOperation(ViewCategoryClass.DISPOSE_ON_CLOSE);
        ViewCategoryClass.setLocationRelativeTo(null);
        this.setVisible(false);
        ViewCategoryClass.openWindowAction();
    }//GEN-LAST:event_viewCategoryBtnActionPerformed

    private void viewCategoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCategoryBtnMouseExited
        viewCategoryBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewCategoryBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_viewCategoryBtnMouseExited

    private void viewCategoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewCategoryBtnMouseEntered
        viewCategoryBtn.setBackground(new java.awt.Color(250, 250, 250));
        viewCategoryBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_viewCategoryBtnMouseEntered

    private void viewBranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBranchBtnActionPerformed
        // TODO add your handling code here:
        ViewBranchClass.setVisible(true);
        ViewBranchClass.setDefaultCloseOperation(ViewBranchClass.DISPOSE_ON_CLOSE);
        ViewBranchClass.setLocationRelativeTo(null);
        ViewBranchClass.openWindowAction();
        this.setVisible(false);

    }//GEN-LAST:event_viewBranchBtnActionPerformed

    private void viewBranchBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBranchBtnMouseExited
        viewBranchBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewBranchBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_viewBranchBtnMouseExited

    private void viewBranchBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBranchBtnMouseEntered
        viewBranchBtn.setBackground(new java.awt.Color(250, 250, 250));
        viewBranchBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_viewBranchBtnMouseEntered

    private void viewProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductsBtnActionPerformed
        // TODO add your handling code here:
        ViewProductsClass.setVisible(true);
        ViewProductsClass.setDefaultCloseOperation(ViewProductsClass.DISPOSE_ON_CLOSE);
        ViewProductsClass.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_viewProductsBtnActionPerformed

    private void viewProductsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProductsBtnMouseExited
        viewProductsBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewProductsBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_viewProductsBtnMouseExited

    private void viewProductsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProductsBtnMouseEntered
        viewProductsBtn.setBackground(new java.awt.Color(250, 250, 250));
        viewProductsBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_viewProductsBtnMouseEntered

    private void viewTransactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionBtnActionPerformed
        // TODO add your handling code here:

        ViewTransactionsClass.setVisible(true);
        ViewTransactionsClass.setDefaultCloseOperation(ViewTransactionsClass.HIDE_ON_CLOSE);
        ViewTransactionsClass.setLocationRelativeTo(null);
        this.setVisible(false);
        ViewTransactionsClass.openWindowAction();
    }//GEN-LAST:event_viewTransactionBtnActionPerformed

    private void viewTransactionBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTransactionBtnMouseExited
        viewTransactionBtn.setBackground(new java.awt.Color(178, 190, 195));
        viewTransactionBtn.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_viewTransactionBtnMouseExited

    private void viewTransactionBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTransactionBtnMouseEntered
        viewTransactionBtn.setBackground(new java.awt.Color(250, 250, 250));
        viewTransactionBtn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_viewTransactionBtnMouseEntered

    private void newItemsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newItemsLabelMouseExited
        newItemsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gNewitems.png")));
    }//GEN-LAST:event_newItemsLabelMouseExited

    private void editItemsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editItemsLabelMouseExited
        editItemsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gEdititems.png")));
    }//GEN-LAST:event_editItemsLabelMouseExited

    private void transactionLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionLabelMouseExited
        transactionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gTrans.png")));
    }//GEN-LAST:event_transactionLabelMouseExited

    private void viewLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLabelMouseEntered
        viewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/wView.png")));
    }//GEN-LAST:event_viewLabelMouseEntered

    private void viewLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLabelMouseExited
        viewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gView.png")));
    }//GEN-LAST:event_viewLabelMouseExited

    private void reportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseEntered
        reportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/wReport.png")));
    }//GEN-LAST:event_reportLabelMouseEntered

    private void reportLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseExited
        reportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gReport.png")));
    }//GEN-LAST:event_reportLabelMouseExited

    private void userLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseExited
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/gUsers.png")));
    }//GEN-LAST:event_userLabelMouseExited

    private void companyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyNameMouseClicked
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_companyNameMouseClicked

    private void editFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFileBtnActionPerformed
        JFileChooser chooser = new JFileChooser("D:\\");
        chooser.setDialogTitle("choosertitle");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            fileLocationLabel.setText(chooser.getSelectedFile().toString() + "\\");
        } else {
          System.out.println("No Selection ");
        }
        
    }//GEN-LAST:event_editFileBtnActionPerformed

    private void saveBackupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBackupBtnActionPerformed
        int confirmation = 0;
        String message = "<html><body><p width='250px' align='center'>Do you want to save the database in the specified location?<br>NOTE: If the file already exists, the file would be overwritten</p></body></html>";
        confirmation = JOptionPane.showConfirmDialog (this, message,"Message",JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION){
            saveBackUp();
        }
        
        
        
    }//GEN-LAST:event_saveBackupBtnActionPerformed

    private void loadBackupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBackupBtnActionPerformed
        int confirmation = 0;
        String message = "<html><body><p width='250px' align='center'>Do you want to load the database in the specified location?<br>NOTE: All the data would be overwritten</p></body></html>";
        confirmation = JOptionPane.showConfirmDialog (this, message, "Message",JOptionPane.YES_NO_OPTION);
        if (confirmation == JOptionPane.YES_OPTION){
            loadBackUp();
        }
        
    }//GEN-LAST:event_loadBackupBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        saveBackUp();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        
    }//GEN-LAST:event_formWindowDeactivated

    private void newSubCategoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSubCategoryBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_newSubCategoryBtnMouseEntered

    private void newSubCategoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newSubCategoryBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_newSubCategoryBtnMouseExited

    private void newSubCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSubCategoryBtnActionPerformed
        
        NewSubCategoryClass.setVisible(true);
        NewSubCategoryClass.setDefaultCloseOperation(NewSubCategoryClass.DISPOSE_ON_CLOSE);
        NewSubCategoryClass.setLocationRelativeTo(null);
        this.setVisible(false);
        NewSubCategoryClass.openWindowAction();
    }//GEN-LAST:event_newSubCategoryBtnActionPerformed

    private void editSubCategoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSubCategoryBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_editSubCategoryBtnMouseEntered

    private void editSubCategoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSubCategoryBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_editSubCategoryBtnMouseExited

    private void editSubCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSubCategoryBtnActionPerformed
        // TODO add your handling code here:
        EditSubCategoryClass.setVisible(true);
        EditSubCategoryClass.setDefaultCloseOperation(EditSubCategoryClass.DISPOSE_ON_CLOSE);
        EditSubCategoryClass.setLocationRelativeTo(null);  
        this.setVisible(false);
        EditSubCategoryClass.openWindowAction();
    }//GEN-LAST:event_editSubCategoryBtnActionPerformed
    
    public void saveBackUp(){
        String executeCmd = "";
        String dbUser = KsuFinal.user;
        String dbPass = KsuFinal.pass;
        String dbName = "expenses";
        
        executeCmd = "mysqldump -u "+dbUser+" -p"+dbPass+" "+dbName+" -r" + fileLocationLabel.getText() + "backup.sql";
        try{
            Process runtimeProcess =Runtime.getRuntime().exec(executeCmd);
            int processComplete = runtimeProcess.waitFor();
            
            if(processComplete == 0){
                JOptionPane.showMessageDialog(this,"Backup Database successfully saved");
            } else{
                JOptionPane.showMessageDialog(this,"The location is invalid", "Error!", JOptionPane.ERROR_MESSAGE);

            }
            
        }catch(Exception ex){
            
        }
    }
    
    public void loadBackUp(){
        String[] executeCmd = {};
        String dbUser = KsuFinal.user;
        String dbPass = KsuFinal.pass;
        String dbName = "expenses";
        
        executeCmd = new String[]{"mysql", dbName, "--user=" + dbUser,"--password=" + dbPass, "-e", " source " + fileLocationLabel.getText() + "backup.sql"};
        
        try{
            Process runtimeProcess =Runtime.getRuntime().exec(executeCmd);
            int processComplete = runtimeProcess.waitFor();
            
            if(processComplete == 0){
                JOptionPane.showMessageDialog(this,"Backup Database successfully loaded");
            } else{
                JOptionPane.showMessageDialog(this,"File is not found in the specified location", "Error!", JOptionPane.ERROR_MESSAGE);

            }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    
    public void openWindowAction(){
        try{
            
            ResultSet rs = KsuFinal.con.createStatement().executeQuery("SELECT * FROM expenses.inventoryinfo;");

            rs.next();

            String cn = rs.getString("title");
            String bl = rs.getString("backupLocation");


            companyName.setText(cn);
            
            String paragraph = "Welcome to " + cn;
            welcomeLabel.setText("<html><p>"+paragraph+"</p></html>");
            fileLocationLabel.setText(bl);
            
           
            
        }catch(Exception ex){
            
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel companyName;
    private javax.swing.JButton editBranchBtn;
    private javax.swing.JButton editCategoryBtn;
    private javax.swing.JButton editFileBtn;
    private javax.swing.JButton editInventoryInfoBtn;
    private javax.swing.JLabel editItemsLabel;
    private javax.swing.JButton editProductBtn;
    private javax.swing.JButton editSubCategoryBtn;
    private javax.swing.JButton editSuppliersBtn;
    private javax.swing.JButton editTransactionBtn;
    private javax.swing.JButton editUnitBtn;
    private javax.swing.JTextField fileLocationLabel;
    private javax.swing.JLabel firstNameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lastNameTF;
    private javax.swing.JButton loadBackupBtn;
    private javax.swing.JButton newBranchBtn;
    private javax.swing.JButton newCategoryBtn;
    private javax.swing.JLabel newItemsLabel;
    private javax.swing.JButton newProductBtn;
    private javax.swing.JButton newSubCategoryBtn;
    private javax.swing.JButton newSupplierBtn;
    private javax.swing.JButton newUnitBtn;
    private javax.swing.JButton receiveWithdrawItemsBtn;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JButton saveBackupBtn;
    private javax.swing.JLabel transactionLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JButton viewBranchBtn;
    private javax.swing.JButton viewCategoryBtn;
    private javax.swing.JLabel viewLabel;
    private javax.swing.JButton viewProductsBtn;
    private javax.swing.JButton viewSupplierBtn;
    private javax.swing.JButton viewTransactionBtn;
    private javax.swing.JButton viewUnitsBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
