    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ksufinal;

import javax.swing.JOptionPane;

/**
 *
 * @author Ricky
 */
public class Menu extends javax.swing.JFrame {
    login t = new login();
    Transaction transactionClass = new Transaction();
    AddProduct addProductClass = new AddProduct();
    editProduct editProductClass = new editProduct();
    addSupplier addSupplierClass = new addSupplier();
    prodDis prodDisClass = new prodDis();
    report reportClass = new report();
    addUnit addUnitClass = new addUnit();
    TransReport transReportClass = new TransReport();
    adProd adProdClass = new adProd();
    editTransaction editTransactionClass = new editTransaction();
    editUnit editUnitClass = new editUnit();
    editBranch editBranchClass = new editBranch();
    editSupplier editSupplierClass = new editSupplier();
    addCategory addCategoryClass = new addCategory();

    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NewProductMenu = new javax.swing.JMenuItem();
        NewUnitMenu = new javax.swing.JMenuItem();
        newSupplierMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        EditProductMenu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ReceiveWithdrawMenu = new javax.swing.JMenuItem();
        EditTransactionMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ViewTransactionMenu = new javax.swing.JMenuItem();
        ViewProductsMenu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        CreateReportMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel1.setText("KSU INVENTORY SYSTEM");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel2.setText("Welcome");

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("New Items");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        NewProductMenu.setText("New product");
        NewProductMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductMenuActionPerformed(evt);
            }
        });
        jMenu1.add(NewProductMenu);

        NewUnitMenu.setText("New unit");
        NewUnitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUnitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(NewUnitMenu);

        newSupplierMenu.setText("New Supplier");
        newSupplierMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSupplierMenuActionPerformed(evt);
            }
        });
        jMenu1.add(newSupplierMenu);

        jMenuItem1.setText("New Branch");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("New Category");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Edit Items");

        EditProductMenu.setText("Edit Product");
        EditProductMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProductMenuActionPerformed(evt);
            }
        });
        jMenu5.add(EditProductMenu);

        jMenuItem2.setText("Edit Unit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Edit Supplier");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Edit Branch");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Transaction");

        ReceiveWithdrawMenu.setText("Recieve/Withdraw items");
        ReceiveWithdrawMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiveWithdrawMenuActionPerformed(evt);
            }
        });
        jMenu2.add(ReceiveWithdrawMenu);

        EditTransactionMenu.setText("Edit Transaction");
        EditTransactionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTransactionMenuActionPerformed(evt);
            }
        });
        jMenu2.add(EditTransactionMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        ViewTransactionMenu.setText("View Transactions");
        ViewTransactionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTransactionMenuActionPerformed(evt);
            }
        });
        jMenu3.add(ViewTransactionMenu);

        ViewProductsMenu.setText("View Products");
        ViewProductsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductsMenuActionPerformed(evt);
            }
        });
        jMenu3.add(ViewProductsMenu);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Report");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        CreateReportMenu.setText("Create Report");
        CreateReportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateReportMenuActionPerformed(evt);
            }
        });
        jMenu4.add(CreateReportMenu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jButton1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewUnitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUnitMenuActionPerformed
       
        addUnitClass.setVisible(true);
        addUnitClass.setDefaultCloseOperation(addUnitClass.HIDE_ON_CLOSE);
        addUnitClass.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_NewUnitMenuActionPerformed

    private void ViewTransactionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTransactionMenuActionPerformed
        
        transReportClass.setVisible(true);
        transReportClass.setDefaultCloseOperation(transReportClass.HIDE_ON_CLOSE);
        transReportClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ViewTransactionMenuActionPerformed

    private void NewProductMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductMenuActionPerformed
        // TODO add your handling code here:
//          AddProduct adPrdct = new AddProduct();
        addProductClass.setVisible(true);
        addProductClass.setDefaultCloseOperation(addProductClass.HIDE_ON_CLOSE);
        addProductClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_NewProductMenuActionPerformed

    private void ReceiveWithdrawMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiveWithdrawMenuActionPerformed
        // TODO add your handling code here:
        
        transactionClass.setVisible(true);
        transactionClass.setDefaultCloseOperation(transactionClass.HIDE_ON_CLOSE);
        transactionClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ReceiveWithdrawMenuActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
        addProductClass.setVisible(true);
        addProductClass.setDefaultCloseOperation(addProductClass.HIDE_ON_CLOSE);
        addProductClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void EditProductMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProductMenuActionPerformed

//        editProductClass.setVisible(true);
//        editProductClass.setDefaultCloseOperation(editProductClass.HIDE_ON_CLOSE);
//        adProd adProdClass = new adProd();
        adProdClass.setVisible(true);
        adProdClass.setDefaultCloseOperation(adProdClass.HIDE_ON_CLOSE);
        adProdClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_EditProductMenuActionPerformed

    private void newSupplierMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSupplierMenuActionPerformed
       
        addSupplierClass.setVisible(true);
        addSupplierClass.setDefaultCloseOperation(addSupplierClass.HIDE_ON_CLOSE);
        addSupplierClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_newSupplierMenuActionPerformed

    private void ViewProductsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductsMenuActionPerformed
        prodDisClass.setVisible(true);
        prodDisClass.setDefaultCloseOperation(prodDisClass.HIDE_ON_CLOSE);
        prodDisClass.setLocationRelativeTo(null);
        this.setVisible(false);
        
    }//GEN-LAST:event_ViewProductsMenuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabel3.setText(t.full);
    }//GEN-LAST:event_formWindowOpened

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void CreateReportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateReportMenuActionPerformed
        reportClass.setVisible(true);
        reportClass.setDefaultCloseOperation(reportClass.HIDE_ON_CLOSE);
        reportClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_CreateReportMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void EditTransactionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTransactionMenuActionPerformed
        editTransactionClass.setVisible(true);
        editTransactionClass.setDefaultCloseOperation(editTransactionClass.HIDE_ON_CLOSE);
        editTransactionClass.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_EditTransactionMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        editUnitClass.setVisible(true);
        editUnitClass.setDefaultCloseOperation(editUnitClass.HIDE_ON_CLOSE);
        editUnitClass.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        editSupplierClass.setVisible(true);
        editSupplierClass.setDefaultCloseOperation(editSupplierClass.HIDE_ON_CLOSE);
        editSupplierClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        editBranchClass.setVisible(true);
        editBranchClass.setDefaultCloseOperation(editBranchClass.HIDE_ON_CLOSE);
        editBranchClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int log = 0;
        log = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Warning",JOptionPane.YES_NO_OPTION);
        if(log == JOptionPane.YES_OPTION){
            this.dispose();
            transReportClass.dispose();
            t.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        addCategoryClass.setVisible(true);
        addCategoryClass.setDefaultCloseOperation(addCategoryClass.HIDE_ON_CLOSE);
        addCategoryClass.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CreateReportMenu;
    private javax.swing.JMenuItem EditProductMenu;
    private javax.swing.JMenuItem EditTransactionMenu;
    private javax.swing.JMenuItem NewProductMenu;
    private javax.swing.JMenuItem NewUnitMenu;
    private javax.swing.JMenuItem ReceiveWithdrawMenu;
    private javax.swing.JMenuItem ViewProductsMenu;
    private javax.swing.JMenuItem ViewTransactionMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem newSupplierMenu;
    // End of variables declaration//GEN-END:variables
}
