/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ksufinal;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Viver
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    static String databaseTableName = "";
    static ResultSet rs;
    static sortProduct sortProductClass2 = new sortProduct("report");
    static sortCategory sortCategoryClass2 = new sortCategory("report");
    static sortUOM sortUOMClass2 = new sortUOM("report");
    static sortBS sortBSClass2 = new sortBS("report");
    
    static ArrayList<String> columnArr = new ArrayList<String>();
    
    static String deliveryWithdrawStatement = "";
    static int onceOnly = 0;
    
    
    public report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TransactionCB = new javax.swing.JCheckBox();
        TransactionNoCB = new javax.swing.JCheckBox();
        ProductNoCB = new javax.swing.JCheckBox();
        DateCB = new javax.swing.JCheckBox();
        ProductNameCB = new javax.swing.JCheckBox();
        CategoryCB = new javax.swing.JCheckBox();
        StandardPriceCB = new javax.swing.JCheckBox();
        QuantityCB = new javax.swing.JCheckBox();
        MinimumCB = new javax.swing.JCheckBox();
        PriceCB = new javax.swing.JCheckBox();
        UnitOfMeasureCB = new javax.swing.JCheckBox();
        ActionCB = new javax.swing.JCheckBox();
        TotalPriceCB = new javax.swing.JCheckBox();
        SupplierBranchCB = new javax.swing.JCheckBox();
        BelowMinimumCB = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        withdrawCB = new javax.swing.JCheckBox();
        deliveryCB = new javax.swing.JCheckBox();
        UOMSortTF = new javax.swing.JTextField();
        CategorySortTF = new javax.swing.JTextField();
        BSSortTF = new javax.swing.JTextField();
        prodSortTF = new javax.swing.JTextField();
        filterProdBtn = new javax.swing.JButton();
        filterCategoryBtn = new javax.swing.JButton();
        filterBSBtn = new javax.swing.JButton();
        filterUOMBtn = new javax.swing.JButton();
        editDateCB = new javax.swing.JCheckBox();
        fromDateChooser = new com.toedter.calendar.JDateChooser();
        toDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        changePeriodBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        reportTable.setAutoCreateRowSorter(true);
        reportTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(reportTable);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Filters");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Columns");

        TransactionCB.setSelected(true);
        TransactionCB.setText("Transaction");
        TransactionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionCBActionPerformed(evt);
            }
        });

        TransactionNoCB.setText("Transaction No.");
        TransactionNoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionNoCBActionPerformed(evt);
            }
        });

        ProductNoCB.setText("Product No.");
        ProductNoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNoCBActionPerformed(evt);
            }
        });

        DateCB.setText("Date");
        DateCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateCBActionPerformed(evt);
            }
        });

        ProductNameCB.setText("Product Name");
        ProductNameCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameCBActionPerformed(evt);
            }
        });

        CategoryCB.setText("Category");
        CategoryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryCBActionPerformed(evt);
            }
        });

        StandardPriceCB.setText("Standard Price");
        StandardPriceCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardPriceCBActionPerformed(evt);
            }
        });

        QuantityCB.setText("Quantity");
        QuantityCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityCBActionPerformed(evt);
            }
        });

        MinimumCB.setText("Minimum Quant.");
        MinimumCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimumCBActionPerformed(evt);
            }
        });

        PriceCB.setText("Price");
        PriceCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceCBActionPerformed(evt);
            }
        });

        UnitOfMeasureCB.setText("Unit of Measure");
        UnitOfMeasureCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitOfMeasureCBActionPerformed(evt);
            }
        });

        ActionCB.setText("Withdraw/ Deposit");
        ActionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionCBActionPerformed(evt);
            }
        });

        TotalPriceCB.setText("Total Price");
        TotalPriceCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceCBActionPerformed(evt);
            }
        });

        SupplierBranchCB.setText("Supplier/Branch");
        SupplierBranchCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierBranchCBActionPerformed(evt);
            }
        });

        BelowMinimumCB.setText("Below minimum");
        BelowMinimumCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BelowMinimumCBActionPerformed(evt);
            }
        });

        jLabel3.setText("Product");

        jLabel4.setText("Category");

        jLabel5.setText("Supplier/Branch");

        jLabel6.setText("Unit of measure");

        withdrawCB.setText("Withdraw");
        withdrawCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawCBActionPerformed(evt);
            }
        });

        deliveryCB.setText("Delivery");
        deliveryCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryCBActionPerformed(evt);
            }
        });

        UOMSortTF.setEditable(false);
        UOMSortTF.setText("All");
        UOMSortTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UOMSortTFActionPerformed(evt);
            }
        });

        CategorySortTF.setEditable(false);
        CategorySortTF.setText("All");

        BSSortTF.setEditable(false);
        BSSortTF.setText("All");

        prodSortTF.setEditable(false);
        prodSortTF.setText("All");

        filterProdBtn.setText("Edit");
        filterProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterProdBtnActionPerformed(evt);
            }
        });

        filterCategoryBtn.setText("Edit");
        filterCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterCategoryBtnActionPerformed(evt);
            }
        });

        filterBSBtn.setText("Edit");
        filterBSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBSBtnActionPerformed(evt);
            }
        });

        filterUOMBtn.setText("Edit");
        filterUOMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterUOMBtnActionPerformed(evt);
            }
        });

        editDateCB.setText("Edit Period");
        editDateCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDateCBActionPerformed(evt);
            }
        });

        jLabel7.setText("From");

        jLabel8.setText("To");

        changePeriodBtn.setText("Change Period");
        changePeriodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePeriodBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Print Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(UOMSortTF, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(BSSortTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(CategorySortTF, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(prodSortTF, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(filterCategoryBtn)
                                                    .addComponent(filterBSBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(filterProdBtn))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(filterUOMBtn))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TransactionCB)
                                                    .addComponent(TransactionNoCB)
                                                    .addComponent(ProductNoCB)
                                                    .addComponent(DateCB)
                                                    .addComponent(ProductNameCB))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(MinimumCB)
                                                    .addComponent(CategoryCB)
                                                    .addComponent(PriceCB)
                                                    .addComponent(QuantityCB)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(StandardPriceCB)))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TotalPriceCB)
                                            .addComponent(SupplierBranchCB)
                                            .addComponent(ActionCB)
                                            .addComponent(UnitOfMeasureCB)))
                                    .addComponent(editDateCB))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(deliveryCB)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(toDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(withdrawCB))
                                .addGap(24, 24, 24)
                                .addComponent(changePeriodBtn)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BelowMinimumCB)
                                .addGap(28, 28, 28))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TransactionCB)
                        .addGap(18, 18, 18)
                        .addComponent(TransactionNoCB)
                        .addGap(18, 18, 18)
                        .addComponent(ProductNoCB)
                        .addGap(18, 18, 18)
                        .addComponent(DateCB))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TotalPriceCB)
                                .addGap(18, 18, 18)
                                .addComponent(SupplierBranchCB)
                                .addGap(18, 18, 18)
                                .addComponent(UnitOfMeasureCB))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(QuantityCB)
                                .addGap(18, 18, 18)
                                .addComponent(MinimumCB)
                                .addGap(18, 18, 18)
                                .addComponent(CategoryCB)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StandardPriceCB)
                                    .addComponent(ActionCB))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriceCB)
                            .addComponent(ProductNameCB))))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prodSortTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterProdBtn))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CategorySortTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterCategoryBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BSSortTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterBSBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(UOMSortTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterUOMBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editDateCB)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fromDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(toDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(changePeriodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawCB)
                    .addComponent(deliveryCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BelowMinimumCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TransactionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionCBActionPerformed

        if (TransactionCB.isSelected()){
            
            //disselect
            BelowMinimumCB.setSelected(false);
            StandardPriceCB.setSelected(false);
            MinimumCB.setSelected(false);
            
            //disabled checkbox
            BelowMinimumCB.setEnabled(false);
            StandardPriceCB.setEnabled(false);
            MinimumCB.setEnabled(false);
            
            //enabled checkbox
            TransactionNoCB.setEnabled(true);
            DateCB.setEnabled(true);
            PriceCB.setEnabled(true);
            SupplierBranchCB.setEnabled(true);
            ActionCB.setEnabled(true);
            
            databaseTableName = "producttrans";
            
            BelowMinimumCB.setSelected(false);
            

        }
        else{
            //disselect
            TransactionNoCB.setSelected(false);
            DateCB.setSelected(false);
            PriceCB.setSelected(false);
            SupplierBranchCB.setSelected(false);
            ActionCB.setSelected(false);
            
            //disabled checkbox
            TransactionNoCB.setEnabled(false);
            DateCB.setEnabled(false);
            PriceCB.setEnabled(false);
            SupplierBranchCB.setEnabled(false);
            ActionCB.setEnabled(false);
            
            //enabled checkbox
            BelowMinimumCB.setEnabled(true);
            StandardPriceCB.setEnabled(true);
            MinimumCB.setEnabled(true);

            databaseTableName = "producttable";
            
        }
        
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_TransactionCBActionPerformed

    private void ProductNameCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_ProductNameCBActionPerformed

    private void TransactionNoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionNoCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_TransactionNoCBActionPerformed

    private void ProductNoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNoCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_ProductNoCBActionPerformed

    private void DateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_DateCBActionPerformed

    private void QuantityCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_QuantityCBActionPerformed

    private void MinimumCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimumCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_MinimumCBActionPerformed

    private void CategoryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_CategoryCBActionPerformed

    private void StandardPriceCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardPriceCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_StandardPriceCBActionPerformed

    private void PriceCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_PriceCBActionPerformed

    private void TotalPriceCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_TotalPriceCBActionPerformed

    private void SupplierBranchCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierBranchCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_SupplierBranchCBActionPerformed

    private void UnitOfMeasureCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitOfMeasureCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_UnitOfMeasureCBActionPerformed

    private void ActionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionCBActionPerformed
        setColumnInTable();
        sortFunction();
    }//GEN-LAST:event_ActionCBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            
        //disabled checkbox
        BelowMinimumCB.setEnabled(false);
        StandardPriceCB.setEnabled(false);
        MinimumCB.setEnabled(false);
        
        //disable date
        fromDateChooser.setEnabled(false);
        toDateChooser.setEnabled(false);
        
        changePeriodBtn.setEnabled(false);
        
        databaseTableName = "producttrans";
        setColumnInTable();
    }//GEN-LAST:event_formWindowOpened

    private void filterProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterProdBtnActionPerformed
        sortProductClass2.setVisible(true);
        sortProductClass2.setDefaultCloseOperation(sortProductClass2.HIDE_ON_CLOSE);
        

    }//GEN-LAST:event_filterProdBtnActionPerformed

    private void filterCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterCategoryBtnActionPerformed

        sortCategoryClass2.setVisible(true);
        sortCategoryClass2.setDefaultCloseOperation(sortCategoryClass2.HIDE_ON_CLOSE);
    }//GEN-LAST:event_filterCategoryBtnActionPerformed

    private void filterBSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBSBtnActionPerformed
         sortBSClass2.setVisible(true);
         sortBSClass2.setDefaultCloseOperation(sortBSClass2.HIDE_ON_CLOSE);
    }//GEN-LAST:event_filterBSBtnActionPerformed

    private void filterUOMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterUOMBtnActionPerformed
         sortUOMClass2.setVisible(true);
         sortUOMClass2.setDefaultCloseOperation(sortUOMClass2.HIDE_ON_CLOSE);
    }//GEN-LAST:event_filterUOMBtnActionPerformed

    private void UOMSortTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UOMSortTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UOMSortTFActionPerformed

    private void BelowMinimumCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BelowMinimumCBActionPerformed
        sortFunction();
    }//GEN-LAST:event_BelowMinimumCBActionPerformed

    private void editDateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDateCBActionPerformed
        if (editDateCB.isSelected()){
            fromDateChooser.setEnabled(true);
            toDateChooser.setEnabled(true);
            changePeriodBtn.setEnabled(true);
        }else{
            fromDateChooser.setEnabled(false);
            toDateChooser.setEnabled(false);
            changePeriodBtn.setEnabled(false);
            sortFunction();
        }
    }//GEN-LAST:event_editDateCBActionPerformed

    private void withdrawCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawCBActionPerformed
        sortFunction();
    }//GEN-LAST:event_withdrawCBActionPerformed

    private void deliveryCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryCBActionPerformed
        sortFunction();
    }//GEN-LAST:event_deliveryCBActionPerformed

    private void changePeriodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePeriodBtnActionPerformed
        sortFunction();

    }//GEN-LAST:event_changePeriodBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        printInvoice();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    private void setColumnInTable(){
        DefaultTableModel reportTableModel = (DefaultTableModel) reportTable.getModel();
        
        reportTableModel.setColumnCount(0);
        
        columnArr.clear();
        
        if (TransactionNoCB.isSelected()){
            reportTableModel.addColumn("Transaction No.");
            columnArr.add("TransactionNo");
        }   
    
        if (ProductNoCB.isSelected()){
            reportTableModel.addColumn("Product No.");
            if (databaseTableName.equals("producttrans")){
                columnArr.add("prodID");
            }
            else{
                columnArr.add("productID");
            }
        }
        
        if (DateCB.isSelected()){
            reportTableModel.addColumn("Date");
            columnArr.add("Date");
            editDateCB.setEnabled(true);
        }
        else{
            editDateCB.setEnabled(false);
            editDateCB.setSelected(false);
            fromDateChooser.setEnabled(false);
            toDateChooser.setEnabled(false);
        }
        
        if (ProductNameCB.isSelected()){
            reportTableModel.addColumn("Product Name");
            if (databaseTableName.equals("producttrans")){
                columnArr.add("Name");
            }
            else{
                columnArr.add("productName");
            }
        }
        
        if (QuantityCB.isSelected()){
            reportTableModel.addColumn("Quantity");
            if (databaseTableName.equals("producttrans")){
                columnArr.add("Quantity");
            }
            else{
                columnArr.add("productQuantity");
            }
        }
        
        if (MinimumCB.isSelected()){
            reportTableModel.addColumn("Minimum Quantity");
            columnArr.add("prodMinq");
        }
        
        if (CategoryCB.isSelected()){
            reportTableModel.addColumn("Category");
            filterCategoryBtn.setEnabled(true);
            columnArr.add("Sub");
        }
        else{
            filterCategoryBtn.setEnabled(false);
            CategorySortTF.setText("All");
        }
        
        if (StandardPriceCB.isSelected()){
            reportTableModel.addColumn("Standard Price");
            columnArr.add("standardPrice");
        }
        
        if (PriceCB.isSelected()){
            reportTableModel.addColumn("Price");
            columnArr.add("Price");
        }
        
        if (TotalPriceCB.isSelected()){
            reportTableModel.addColumn("Total Price");
            columnArr.add("TotalPrice");
        }
        
        if (SupplierBranchCB.isSelected()){
            reportTableModel.addColumn("Supplier/Branch");
            filterBSBtn.setEnabled(true);
            columnArr.add("SuppBranch");
        }
        else{
            filterBSBtn.setEnabled(false);
            BSSortTF.setText("All");
        }
        
        if (UnitOfMeasureCB.isSelected()){
            reportTableModel.addColumn("Unit of Measure");
            filterUOMBtn.setEnabled(true);
            if (databaseTableName.equals("producttrans")){
                columnArr.add("Unit");
            }
            else{
                columnArr.add("productUnit");
            }
        }
        else{
            filterUOMBtn.setEnabled(false);
            UOMSortTF.setText("All");
        }
        
        if (ActionCB.isSelected()){
            reportTableModel.addColumn("Action");
            deliveryCB.setEnabled(true);
            withdrawCB.setEnabled(true);
            deliveryCB.setSelected(true);
            withdrawCB.setSelected(true);
            columnArr.add("Action");
        }
        else{
            deliveryCB.setEnabled(false);
            withdrawCB.setEnabled(false);
            deliveryCB.setSelected(false);
            withdrawCB.setSelected(false);
        }
        
        if ((ProductNoCB.isSelected() || ProductNameCB.isSelected()) && TransactionCB.isSelected()){
            filterProdBtn.setEnabled(true);
            
        }
        else{
            filterProdBtn.setEnabled(false);
            prodSortTF.setText("All");
        }
        
    }
    
    public static void sortFunction(){
        DefaultTableModel ReportTableModel = (DefaultTableModel) reportTable.getModel();
        Boolean notChange = true;
        ArrayList<String> strArr = new ArrayList<String>();
        
        if (deliveryCB.isSelected()){
            strArr.add("Action = 'deposit'");
        }
        if (withdrawCB.isSelected()){
            strArr.add("Action = 'withdraw'");
        }
        
        deliveryWithdrawStatement = " (" + String.join(" or ", strArr) + ")";
        
        ArrayList<String> finalArr = new ArrayList<String>();
        
        if(sortProductClass2.prodSortStatement.length() > 5){
            finalArr.add(sortProductClass2.prodSortStatement);
        }
        else if(prodSortTF.getText().equals("All")){
            //do Nothing
        }
        else{
            ReportTableModel.setRowCount(0);
            JOptionPane.showMessageDialog(null,"Please select a product");
            notChange = false;
        }
        
        if (sortUOMClass2.UOMSortStatement.length() > 5){
            finalArr.add(sortUOMClass2.UOMSortStatement);
        }
        else if(UOMSortTF.getText().equals("All")){
            //do Nothing
        }
        else{
            ReportTableModel.setRowCount(0);
            JOptionPane.showMessageDialog(null,"Please select a Unit of Measure");
            notChange = false;
        }
        
        if (sortBSClass2.BSSortStatement.length() > 5){
            finalArr.add(sortBSClass2.BSSortStatement);
        }
        else if(BSSortTF.getText().equals("All")){
            //do Nothing
        }
        else{
            ReportTableModel.setRowCount(0);
            JOptionPane.showMessageDialog(null,"Please select a Branch or Supplier");
            notChange = false;
        }
        
        if (sortCategoryClass2.categorySortStatement.length() > 5){
            finalArr.add(sortCategoryClass2.categorySortStatement);
        }
        else if(CategorySortTF.getText().equals("All")){
            //do Nothing
        }
        else{
            ReportTableModel.setRowCount(0);
            JOptionPane.showMessageDialog(null,"Please select a Category");
            notChange = false;
        }
        
        if (deliveryWithdrawStatement.length() > 5){
            finalArr.add(deliveryWithdrawStatement);
        }
        else if (!ActionCB.isSelected()){
            //do nothing
        }
        else{
            ReportTableModel.setRowCount(0);
            JOptionPane.showMessageDialog(null,"Please select if either withdraw or deposit");
            notChange = false;
        }
        
        if (notChange){

            String finalStatement = "SELECT * FROM expenses." + databaseTableName;

            if (finalArr.size() > 0){
                finalStatement += " WHERE";
                finalStatement += String.join("and", finalArr);
            }

            if (editDateCB.isSelected()){
                try{
                    SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String fdate = dFormat.format(fromDateChooser.getDate()); 
                    String tdate = dFormat.format(toDateChooser.getDate());
                    ReportTableModel.setRowCount(0);
                    try{
                        rs = KsuFinal.con.createStatement().executeQuery(finalStatement);
                        while(rs.next()){
                            
                            ArrayList<String> tempArr = new ArrayList<String>();
                            for (String x: columnArr){
                                if (x.equals("TotalPrice")){
                                    if (databaseTableName.equals("producttrans")){
                                        tempArr.add(String.valueOf(Math.round((Float.parseFloat(rs.getString("Quantity")) * Float.parseFloat(rs.getString("Price"))) * 100) / 100));
                                    }else{
                                        tempArr.add(String.valueOf(Math.round((Float.parseFloat(rs.getString("productQuantity")) * Float.parseFloat(rs.getString("standardPrice"))) * 100) / 100));
                                    }
                                }
                                else{
                                    tempArr.add(rs.getString(x));
                                }
                            }
                            String dt = rs.getString("Date");


                            Date currdate = dFormat.parse(dt);
                            Date fromDate = dFormat.parse(fdate);
                            Date toDate = dFormat.parse(tdate);

                            if (((currdate.after(fromDate) && currdate.before(toDate)) || currdate.equals(fromDate) || currdate.equals(toDate)) && (fromDate.before(toDate) || fromDate.equals(toDate))){
                                
                                if (BelowMinimumCB.isSelected()){
                                    if (Integer.parseInt(rs.getString("productQuantity")) <= Integer.parseInt(rs.getString("prodMinq"))){
                                        String[] item = tempArr.toArray(new String[tempArr.size()]);
                                        ReportTableModel.addRow(item);
                                    }
                                }
                                else{
                                    String[] item = tempArr.toArray(new String[tempArr.size()]);
                                    ReportTableModel.addRow(item);  
                                }
                            }

                        }
//                        JOptionPane.showMessageDialog(this,"Filtered Successfully!");
                    }
                    catch(Exception e){
                        System.out.println(e);
                    }
                }catch(NullPointerException ex){
                    JOptionPane.showMessageDialog(null,"Please input a period or uncheck the Edit Period checkbox");
                }

            }else{
                ReportTableModel.setRowCount(0);
                try{
                    rs = KsuFinal.con.createStatement().executeQuery(finalStatement);
                    while(rs.next()){
                        ArrayList<String> tempArr = new ArrayList<String>();
                        for (String x: columnArr){
                            if (x.equals("TotalPrice")){
                                if (databaseTableName.equals("producttrans")){
                                    tempArr.add(String.valueOf(Math.round((Float.parseFloat(rs.getString("Quantity")) * Float.parseFloat(rs.getString("Price"))) * 100) / 100));
                                }else{
                                    tempArr.add(String.valueOf(Math.round((Float.parseFloat(rs.getString("productQuantity")) * Float.parseFloat(rs.getString("standardPrice"))) * 100) / 100));
                                }
                            }
                            else{
                                tempArr.add(rs.getString(x));
                            }
                        }

                        if (BelowMinimumCB.isSelected()){
                            if (Integer.parseInt(rs.getString("productQuantity")) <= Integer.parseInt(rs.getString("prodMinq"))){
                                String[] item = tempArr.toArray(new String[tempArr.size()]);
                                ReportTableModel.addRow(item);
                            }
                        }
                        else{
                            String[] item = tempArr.toArray(new String[tempArr.size()]);
                            ReportTableModel.addRow(item);  
                        }
                    }
//                    JOptionPane.showMessageDialog(this,"Filtered Successfully!");
                }
                catch(Exception e){
                    System.out.println(e);
                }
            }
        }
    }
    
    public void printInvoice(){
        Document doc = new Document();
        PdfWriter docWriter = null;
        
        String currentDate = java.time.LocalDate.now().toString();
        
        try{
            Font textInvoice = new Font(Font.FontFamily.HELVETICA, 30, Font.BOLD, new BaseColor(0, 0, 0));
            Font textBilledTo = new Font(Font.FontFamily.HELVETICA, 17, Font.BOLD, new BaseColor(0, 0, 0));
            Font textBold12 = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, new BaseColor(0, 0, 0));
            Font text12 = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, new BaseColor(0, 0, 0));
            docWriter = PdfWriter.getInstance(doc, new FileOutputStream("Report.pdf"));
            doc.open();
            int pdfWidth = columnArr.size();
            float perWidth = 100/pdfWidth;
            
            float[] columnWidths = new float[pdfWidth];
            for (int x = 0; x < pdfWidth; x++){
                columnWidths[x] = (float)perWidth;
            }
            for (float x: columnWidths){
                System.out.println(x);
            }
            
            PdfPTable texts = new PdfPTable(columnWidths);
            
            
            Paragraph paragraph = new Paragraph();
            
            createcell(texts, "Date Issued: " + currentDate, Element.ALIGN_RIGHT, pdfWidth, text12, 0, 255, 255, 255);       
            
            createcell(texts, "REPORT", Element.ALIGN_CENTER, pdfWidth, textInvoice, 0, 255, 255, 255);
            createcell(texts, "Branch Name", Element.ALIGN_CENTER, pdfWidth, textBold12, 0, 255, 255, 255);
            createcell(texts, "Street of Branch", Element.ALIGN_CENTER, pdfWidth, text12, 0, 255, 255, 255);
            createcell(texts, "City of Branch", Element.ALIGN_CENTER, pdfWidth, text12, 0, 255, 255, 255);
            createcell(texts, "Contact#: 123456789", Element.ALIGN_CENTER, pdfWidth, text12, 0, 255, 255, 255);
            
            createcell(texts, "______________________________________________________________________________________", Element.ALIGN_CENTER, pdfWidth, text12, 0, 255, 255, 255);
            
            createcell(texts, "PRINTED BY", Element.ALIGN_LEFT, pdfWidth, textBilledTo, 0, 255, 255, 255);     
            createSpace(texts, pdfWidth);
            
            createcell(texts, "LASTNAME, FIRSTNAME", Element.ALIGN_LEFT, pdfWidth, textBold12, 0, 255, 255, 255);
            createSpace(texts, pdfWidth);
            createSpace(texts, pdfWidth);
            
            
            
            for (int x = 0; x < pdfWidth; x++){
                createcell(texts, reportTable.getColumnName(x), Element.ALIGN_CENTER, 1, text12, 0, 179, 179, 179);
            }
            
            
            createSpace(texts, pdfWidth);
//            double totUnitPrice = 0;
            int rowSize = reportTable.getRowCount();
            
            for (int x = 0; x < rowSize; x++){
                for (int y = 0; y < pdfWidth; y++){
                    String value = reportTable.getValueAt(x, y).toString();
                    createcell(texts, value, Element.ALIGN_CENTER, 1, text12, 0, 255, 255, 255);
//                    totUnitPrice += Integer.parseInt(x[5]) * Integer.parseInt(x[4]) ;
                }
                createSpace(texts, pdfWidth);
            }
            
//            createSpace(texts);
//            createcell(texts, "_____________________________________________________________________________", Element.ALIGN_CENTER, 4, text12, 0, 255, 255, 255);
//            createSpace(texts);
//            
//            double tax = totUnitPrice * 0.12;
//            
//            double Total = totUnitPrice + tax;
//            
//            createcell(texts, "Subtotal", Element.ALIGN_RIGHT, 3, textBold12, 0, 255, 255, 255);
//            createcell(texts, String.format("%.2f", totUnitPrice), Element.ALIGN_CENTER, 1, text12, 0, 255, 255, 255);
//            createSpace(texts);
//            
//            createcell(texts, "Tax 12%", Element.ALIGN_RIGHT, 3, textBold12, 0, 255, 255, 255);
//            createcell(texts, String.format("%.2f", tax), Element.ALIGN_CENTER, 1, text12, 0, 255, 255, 255);
//            createSpace(texts);
//            
//            createcell(texts, "Total Cost", Element.ALIGN_RIGHT, 3, textBold12, 0, 255, 255, 255);
//            createcell(texts, String.format("%.2f", Total), Element.ALIGN_CENTER, 1, text12, 0, 255, 255, 255);
            
            
            texts.setWidthPercentage(100f);
            
            paragraph.add(texts);
            doc.add(paragraph);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
        if (doc != null){
            doc.close();
        }
        
        if (docWriter != null){
            docWriter.close();
        }
        
        try{
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "Report.pdf");
        }
        catch(Exception ex){
        }
    }
    
    
    public void createcell(PdfPTable table, String text, int align, int colspan, Font font, int border, int r, int g, int b){
        PdfPCell cell = new PdfPCell(new Phrase(text.trim(), font));
        cell.setHorizontalAlignment(align);
        cell.setColspan(colspan);
        if (border == 0){
            cell.setBorder(Rectangle.NO_BORDER);
        }
        else{
            cell.setBorder(Rectangle.BOX);
        }
        cell.setBackgroundColor(new BaseColor(r, g, b));
        table.addCell(cell);
    }
    
    public void createSpace(PdfPTable table, int pdfWidth){
        PdfPCell cell = new PdfPCell();
        cell.setColspan(pdfWidth);
        cell.setMinimumHeight(15f);
        cell.setBorder(Rectangle.NO_BORDER);
        table.addCell(cell);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox ActionCB;
    public static javax.swing.JTextField BSSortTF;
    public static javax.swing.JCheckBox BelowMinimumCB;
    public static javax.swing.JCheckBox CategoryCB;
    public static javax.swing.JTextField CategorySortTF;
    public static javax.swing.JCheckBox DateCB;
    public static javax.swing.JCheckBox MinimumCB;
    public static javax.swing.JCheckBox PriceCB;
    public static javax.swing.JCheckBox ProductNameCB;
    public static javax.swing.JCheckBox ProductNoCB;
    public static javax.swing.JCheckBox QuantityCB;
    public static javax.swing.JCheckBox StandardPriceCB;
    public static javax.swing.JCheckBox SupplierBranchCB;
    public static javax.swing.JCheckBox TotalPriceCB;
    public static javax.swing.JCheckBox TransactionCB;
    public static javax.swing.JCheckBox TransactionNoCB;
    public static javax.swing.JTextField UOMSortTF;
    public static javax.swing.JCheckBox UnitOfMeasureCB;
    private javax.swing.JButton changePeriodBtn;
    public static javax.swing.JCheckBox deliveryCB;
    public static javax.swing.JCheckBox editDateCB;
    private javax.swing.JButton filterBSBtn;
    private javax.swing.JButton filterCategoryBtn;
    private javax.swing.JButton filterProdBtn;
    private javax.swing.JButton filterUOMBtn;
    public static com.toedter.calendar.JDateChooser fromDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    public static javax.swing.JTextField prodSortTF;
    public static javax.swing.JTable reportTable;
    public static com.toedter.calendar.JDateChooser toDateChooser;
    public static javax.swing.JCheckBox withdrawCB;
    // End of variables declaration//GEN-END:variables
}
