/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ksufinal;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Viver
 */
public class sortBS extends javax.swing.JFrame {
    
    
    ResultSet rs;
    static ArrayList<String> selectedBS = new ArrayList<String>();
    static String  BSSortStatement = "";
    
    
    
    /**
     * Creates new form sortBS
     */
    public sortBS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sortBSTable = new javax.swing.JTable();
        saveBSSortBtn = new javax.swing.JButton();
        selectAllCBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        sortBSTable.setAutoCreateRowSorter(true);
        sortBSTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sortBSTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select the Branch/Supplier here"
            }
        ));
        sortBSTable.setRowHeight(25);
        jScrollPane1.setViewportView(sortBSTable);

        saveBSSortBtn.setText("Save");
        saveBSSortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBSSortBtnActionPerformed(evt);
            }
        });

        selectAllCBox.setText("Select All");
        selectAllCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllCBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectAllCBox)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBSSortBtn))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(selectAllCBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(saveBSSortBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBSSortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBSSortBtnActionPerformed

        selectedBS.clear();
        
        BSSortStatement = "";

        if (selectAllCBox.isSelected()){

            TransReport.BSSortTF.setText("All");
        }
        else{
            int[] sr = sortBSTable.getSelectedRows();
            for (int x = 0; x < sr.length; x++){
                selectedBS.add(sortBSTable.getValueAt(sr[x], 0).toString());
            }
            String jointArray = String.join(", ", selectedBS);
            TransReport.BSSortTF.setText(jointArray);
            
            
            ArrayList<String> strArr = new ArrayList<String>();
            
            for (String x: selectedBS){
                strArr.add("SuppBranch = '" + x + "'");
            }
            
            BSSortStatement = " (" + String.join(" or ", strArr) + ") ";
            
            System.out.println(BSSortStatement);
        }

        this.setVisible(false);

        //        System.out.println(jointArray);
    }//GEN-LAST:event_saveBSSortBtnActionPerformed

    private void selectAllCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllCBoxActionPerformed
        //        DefaultTableModel t = (DefaultTableModel)sortProdTable.getModel();
        if (selectAllCBox.isSelected()){
            sortBSTable.setRowSelectionAllowed(false);
            sortBSTable.setEnabled(false);
            sortBSTable.setForeground(Color.LIGHT_GRAY);
            sortBSTable.setBackground(new Color(236, 236, 236));
        }
        else{
            sortBSTable.setRowSelectionAllowed(true);
            sortBSTable.setEnabled(true);
            sortBSTable.setForeground(Color.black);
            sortBSTable.setBackground(Color.white);
        }
    }//GEN-LAST:event_selectAllCBoxActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel t = (DefaultTableModel)sortBSTable.getModel();
        
        
        try{
            rs = KsuFinal.con.createStatement().executeQuery("SELECT * FROM expenses.suppliertable;");
            while(rs.next()){
                String nm = rs.getString("supplierName");
                String [] nmArr = {nm};
                
                t.addRow(nmArr);
                
            }  
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sortBS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sortBS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sortBS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sortBS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sortBS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveBSSortBtn;
    private javax.swing.JCheckBox selectAllCBox;
    private javax.swing.JTable sortBSTable;
    // End of variables declaration//GEN-END:variables
}
